#!/usr/bin/env node
// Regenerate `packages/ui/src/icons/index.js` from the .svg files in this
// folder's `svg/` subdirectory. Each `<Name>.svg` becomes a `<Name>Icon`
// React export rendered via the shared `makeIcon` helper.
//
// Conventions enforced on every output icon:
//   - viewBox is normalised to `0 0 24 24`.
//   - Every `fill="black"` and `stroke="black"` is rewritten to
//     `currentColor` so the glyph obeys the on-* foreground contract.
//   - Hyphenated SVG attributes are converted to JSX camelCase
//     (`fill-rule` → `fillRule`, `clip-rule` → `clipRule`, …).
//   - A no-op full-viewport `<clipPath><rect 24×24/></clipPath>` wrapper is
//     stripped (Day / DayFill, exported from Figma with a redundant mask).
//   - Keywords are sourced from `keywords.json` (sibling); a fallback split
//     of the PascalCase name is used when the JSON lacks an entry.
//
// Usage: node packages/ui/src/icons/build-icons.mjs

import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve, basename } from "node:path";

const SELF = fileURLToPath(import.meta.url);
const DIR = dirname(SELF);
const SVG_DIR = join(DIR, "svg");
const OUT = join(DIR, "index.js");
const KEYWORDS_PATH = join(DIR, "keywords.json");

const KEYWORD_MAP = existsSync(KEYWORDS_PATH)
  ? JSON.parse(readFileSync(KEYWORDS_PATH, "utf8"))
  : {};

// Aliases — call sites that should keep working after the regeneration but
// don't have a 1:1 svg file. Keep this list small and obvious; new code
// should import the canonical name.
const ALIASES = {
  CopyIcon: "DuplicateIcon",
};

const HYPHENATED_TO_JSX = {
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "fill-opacity": "fillOpacity",
  "stroke-opacity": "strokeOpacity",
  "stroke-dasharray": "strokeDasharray",
  "stroke-dashoffset": "strokeDashoffset",
};

function svgToInnerJsx(raw) {
  // Drop the outer <svg ...> wrapper.
  const m = raw.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!m) throw new Error("no <svg> root");
  let body = m[1].trim();

  // Strip Figma-exported full-viewport clipPath wrappers — `<g clip-path="…">
  // [content] </g>` plus `<defs><clipPath…><rect width="24" height="24"/>
  // </clipPath></defs>`. The clip is a no-op when its rect matches the
  // viewBox.
  body = body.replace(
    /<g\s+clip-path="url\(#[^)]+\)"[^>]*>([\s\S]*?)<\/g>\s*<defs>[\s\S]*?<\/defs>/g,
    "$1",
  );

  // Recolour: any explicit black fill / stroke becomes currentColor so the
  // icon inherits its container's text color.
  body = body
    .replace(/fill="black"/g, 'fill="currentColor"')
    .replace(/stroke="black"/g, 'stroke="currentColor"');

  // Self-close any open <path .../> and similar leaf nodes if the source
  // used `<path …></path>` form. Most exports use self-closing already.
  // No transform needed; JSX accepts both.

  // Convert hyphenated attribute names to JSX camelCase.
  for (const [from, to] of Object.entries(HYPHENATED_TO_JSX)) {
    const re = new RegExp(`\\b${from}=`, "g");
    body = body.replace(re, `${to}=`);
  }

  // Collapse internal whitespace runs so the emitted JSX is single-line per
  // element — keeps the output diff readable.
  body = body
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .join("");

  return body;
}

function keywordsFor(name) {
  if (KEYWORD_MAP[name]) return KEYWORD_MAP[name];
  // Fall back to the lowercased PascalCase split — `BackwardCircleFill` →
  // ['backward', 'circle', 'fill']. Better than an empty array for search.
  return name
    .replace(/([A-Z])/g, " $1")
    .trim()
    .toLowerCase()
    .split(/\s+/);
}

function pascalToIconName(stem) {
  return `${stem}Icon`;
}

function main() {
  const files = readdirSync(SVG_DIR)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  const entries = files.map((file) => {
    const stem = basename(file, ".svg");
    const name = pascalToIconName(stem);
    const raw = readFileSync(join(SVG_DIR, file), "utf8");
    const inner = svgToInnerJsx(raw);
    const keywords = keywordsFor(name);
    return { name, stem, inner, keywords };
  });

  const head = `/* AUTO-GENERATED by packages/ui/src/icons/build-icons.mjs
   from the .svg files in ./svg. Do not edit by hand — re-run the script
   to regenerate. Keyword overrides live in ./keywords.json. */

function makeIcon(name, render, keywords = []) {
  function Icon({ size = 20, ...props }) {
    return (
      <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
        {...props}
      >
        {render}
      </svg>
    );
  }
  Icon.displayName = name;
  Icon.keywords = keywords;
  return Icon;
}
`;

  const decls = entries
    .map(
      ({ name, inner, keywords }) =>
        `export const ${name} = makeIcon(\n  '${name}',\n  <>${inner}</>,\n  ${JSON.stringify(keywords)},\n);`,
    )
    .join("\n\n");

  const aliasDecls = Object.entries(ALIASES)
    .map(([alias, target]) => `export const ${alias} = ${target};`)
    .join("\n");

  const registryEntries = [
    ...entries.map(({ name }) => `  ${name},`),
    ...Object.keys(ALIASES).map((alias) => `  ${alias},`),
  ].join("\n");

  const registry = `\nexport const icons = {\n${registryEntries}\n};\n`;

  writeFileSync(
    OUT,
    `${head}\n${decls}\n\n/* Semantic aliases — call sites importing these names continue to\n   resolve; the underlying glyph is the canonical icon. */\n${aliasDecls}\n${registry}`,
  );

  console.log(`Wrote ${entries.length} icons + ${Object.keys(ALIASES).length} aliases → ${OUT}`);
}

main();
