import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  component: Index,
});

function Index() {
  return (
    <div
      className="min-h-screen px-6 py-16"
      style={{
        background: "var(--sys-color-surface)",
        color: "var(--sys-color-onSurface)",
      }}
    >
      <div className="mx-auto max-w-2xl">
        <p
          className="text-sm font-medium tracking-wide uppercase"
          style={{ color: "var(--sys-color-onSurfaceVariant)" }}
        >
          Chorus .md
        </p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight">
          The design system behind a product built on the belief that your voice matters.
        </h1>
        <p
          className="mt-6 text-base leading-relaxed"
          style={{ color: "var(--sys-color-onSurfaceVariant)" }}
        >
          Individual voices arranged into harmony through tokens every surface sings from.
          This is the Lovable-exported view of Chorus — the same tokens, ported into a
          TanStack Start + Tailwind v4 shell that the Lovable editor can extend.
        </p>

        <div
          className="mt-10 rounded-lg border p-6"
          style={{
            borderColor: "var(--sys-color-outlineVariant)",
            background: "var(--sys-color-surfaceContainerLow)",
          }}
        >
          <p
            className="text-xs font-medium tracking-wide uppercase"
            style={{ color: "var(--sys-color-onSurfaceVariant)" }}
          >
            Tokens are live
          </p>
          <p className="mt-2 text-sm">
            This card uses <code>--sys-color-surfaceContainerLow</code> and{" "}
            <code>--sys-color-outlineVariant</code> from the chorus token system,
            generated by <code>scripts/build-lovable.mjs</code>.
          </p>
        </div>
      </div>
    </div>
  );
}
