#!/usr/bin/env node
// Generate Kotlin sources for Jetpack Compose from schema/tokens/resolved.*.json.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseTokens, camel, pascal } from "./lib/parse-tokens.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = process.env.CHORUS_TOKENS_ANDROID_OUT_DIR
  ? resolve(process.env.CHORUS_TOKENS_ANDROID_OUT_DIR)
  : resolve(
      here,
      "../chorus-tokens/src/main/kotlin/dev/blinddsai/chorus/tokens/generated",
    );
mkdirSync(outDir, { recursive: true });

const PACKAGE = "dev.blinddsai.chorus.tokens.generated";

const header = (extraImports = "") => `// Auto-generated by packages/tokens-android/scripts/codegen.mjs.
// Do not edit by hand. Run \`npm run codegen\` after touching schema/tokens.
package ${PACKAGE}

${extraImports}`;

const composeHex = (hex) => {
  const h = hex.replace("#", "").toLowerCase();
  let r, g, b, a;
  if (h.length === 3) {
    r = parseInt(h[0] + h[0], 16);
    g = parseInt(h[1] + h[1], 16);
    b = parseInt(h[2] + h[2], 16);
    a = 255;
  } else if (h.length === 6) {
    r = parseInt(h.slice(0, 2), 16);
    g = parseInt(h.slice(2, 4), 16);
    b = parseInt(h.slice(4, 6), 16);
    a = 255;
  } else if (h.length === 8) {
    r = parseInt(h.slice(0, 2), 16);
    g = parseInt(h.slice(2, 4), 16);
    b = parseInt(h.slice(4, 6), 16);
    a = parseInt(h.slice(6, 8), 16);
  } else {
    throw new Error(`unsupported color literal: ${hex}`);
  }
  const argb = ((a << 24) | (r << 16) | (g << 8) | b) >>> 0;
  return `Color(0x${argb.toString(16).padStart(8, "0").toUpperCase()})`;
};

const t = parseTokens();

// -------- ChorusColors.kt ---------------------------------------------
{
  const keys = Object.keys(t.colorsLight).sort();
  const lightProps = keys
    .map((k) => `    val ${camel(k.split("-"))}: Color = ${composeHex(t.colorsLight[k])},`)
    .join("\n");
  const darkArgs = keys
    .map((k) => `        ${camel(k.split("-"))} = ${composeHex(t.colorsDark[k] ?? t.colorsLight[k])},`)
    .join("\n");
  const lightArgs = keys
    .map((k) => `        ${camel(k.split("-"))} = ${composeHex(t.colorsLight[k])},`)
    .join("\n");

  const body = `${header(`import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
`)}
@Immutable
data class ChorusColors(
${lightProps.replace(/,$/, "")}
)

val ChorusColorsLight: ChorusColors = ChorusColors(
${lightArgs.replace(/,$/, "")}
)

val ChorusColorsDark: ChorusColors = ChorusColors(
${darkArgs.replace(/,$/, "")}
)
`;
  writeFileSync(resolve(outDir, "ChorusColors.kt"), body);
}

// -------- ChorusPalette.kt (ref.palette.*) ----------------------------
{
  const families = Object.keys(t.palette).sort();
  let blocks = "";
  for (const family of families) {
    blocks += `    object ${pascal(family)} {\n`;
    for (const step of Object.keys(t.palette[family]).sort((a, b) => Number(a) - Number(b))) {
      blocks += `        val ${camel(["s" + step])}: Color = ${composeHex(t.palette[family][step])}\n`;
    }
    blocks += `    }\n\n`;
  }
  const body = `${header(`import androidx.compose.ui.graphics.Color
`)}
/**
 * ref.palette.* — flat reference colors. Most components should reach
 * for ChorusTheme.colors (sys.color.*) instead; this is exposed for the
 * rare component (e.g., Chip tag) whose spec explicitly references a
 * translucent neutral that must adapt to whatever surface sits behind.
 */
object ChorusPalette {
${blocks.trimEnd()}
}
`;
  writeFileSync(resolve(outDir, "ChorusPalette.kt"), body);
}

// -------- ChorusDimensions.kt -----------------------------------------
{
  const dpBlock = (clsName, map) => {
    const lines = Object.keys(map)
      .sort()
      .map((k) => `    val ${camel(k.split("-"))}: Dp = ${map[k]}.dp`)
      .join("\n");
    return `object ${clsName} {\n${lines}\n}`;
  };

  const layoutGroups = ["container", "inline", "stack", "page"]
    .map((g) => `    object ${pascal(g)} {\n${Object.keys(t.layout[g])
      .sort()
      .map((k) => `        val ${camel(k.split("-"))}: Dp = ${t.layout[g][k]}.dp`)
      .join("\n")}\n    }`)
    .join("\n\n");

  const stateLines = Object.keys(t.state)
    .sort()
    .map((k) => `    val ${camel(k.split("-"))}: Float = ${t.state[k]}f`)
    .join("\n");

  const body = `${header(`import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
`)}
object ChorusLayout {
${layoutGroups}
}

${dpBlock("ChorusRadius", t.radius)}

${dpBlock("ChorusBorderWidth", t.borderWidth)}

${dpBlock("ChorusIconSize", t.iconSize)}

object ChorusStateOpacity {
${stateLines}
}
`;
  writeFileSync(resolve(outDir, "ChorusDimensions.kt"), body);
}

// -------- ChorusTypography.kt -----------------------------------------
{
  const trackingEm = (tracking) => {
    const m = /^(-?\d*\.?\d+)em$/.exec(tracking);
    return m ? Number(m[1]) : 0;
  };
  const weightConst = (n) => {
    const table = {
      100: "FontWeight.Thin",
      200: "FontWeight.ExtraLight",
      300: "FontWeight.Light",
      400: "FontWeight.Normal",
      500: "FontWeight.Medium",
      600: "FontWeight.SemiBold",
      700: "FontWeight.Bold",
      800: "FontWeight.ExtraBold",
      900: "FontWeight.Black",
    };
    return table[n] ?? "FontWeight.Normal";
  };

  let body = `${header(`import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
`)}
object ChorusTypography {
`;

  for (const role of Object.keys(t.typography).sort()) {
    body += `    object ${pascal(role)} {\n`;
    for (const size of Object.keys(t.typography[role]).sort()) {
      const v = t.typography[role][size];
      const tracking = trackingEm(v.tracking);
      body += `        val ${camel(size.split("-"))}: TextStyle = TextStyle(\n`;
      body += `            fontSize = ${v.size}.sp,\n`;
      body += `            fontWeight = ${weightConst(v.weight)},\n`;
      body += `            lineHeight = ${(v.size * v.lineHeight).toFixed(2)}.sp,\n`;
      body += `            letterSpacing = ${tracking}.em,\n`;
      body += `        )\n`;
    }
    body += `    }\n\n`;
  }
  body += `}\n`;

  writeFileSync(resolve(outDir, "ChorusTypography.kt"), body);
}

console.log("[tokens-android] generated ChorusColors.kt, ChorusPalette.kt, ChorusDimensions.kt, ChorusTypography.kt");
