#!/usr/bin/env node
// Generate Swift sources under Sources/ChorusTokens/Generated from
// schema/tokens/resolved.*.json. Re-run on every token release.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseTokens, camel, pascal, parseHex } from "./lib/parse-tokens.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = process.env.CHORUS_TOKENS_IOS_OUT_DIR
  ? resolve(process.env.CHORUS_TOKENS_IOS_OUT_DIR)
  : resolve(here, "../Sources/ChorusTokens/Generated");
mkdirSync(outDir, { recursive: true });

const header = `// Auto-generated by packages/tokens-ios/scripts/codegen.mjs.
// Do not edit by hand. Run \`npm run codegen\` after touching schema/tokens.

import SwiftUI
`;

const swiftHex = (hex) => {
  const { r, g, b, a } = parseHex(hex);
  const f = (n) => (n / 255).toFixed(4);
  return `Color(.sRGB, red: ${f(r)}, green: ${f(g)}, blue: ${f(b)}, opacity: ${f(a)})`;
};

const t = parseTokens();

// -------- Colors.swift -------------------------------------------------
{
  const keys = Object.keys(t.colorsLight).sort();
  const lightCases = keys
    .map((k) => `    public static let ${camel(k.split("-"))} = ${swiftHex(t.colorsLight[k])}`)
    .join("\n");
  const darkCases = keys
    .map((k) => `    public static let ${camel(k.split("-"))} = ${swiftHex(t.colorsDark[k] ?? t.colorsLight[k])}`)
    .join("\n");
  const themed = keys
    .map((k) => {
      const name = camel(k.split("-"));
      return `    public var ${name}: Color { dark ? ChorusColors.Dark.${name} : ChorusColors.Light.${name} }`;
    })
    .join("\n");

  const body = `${header}
public enum ChorusColors {
    public enum Light {
${lightCases}
    }

    public enum Dark {
${darkCases}
    }
}

/// Theme-aware accessor. Resolve once via \`ChorusColors.themed(for: colorScheme)\`
/// or read inside a SwiftUI view with \`@Environment(\\.colorScheme)\`.
public struct ChorusThemedColors {
    public let dark: Bool

${themed}
}

public extension ChorusColors {
    static func themed(for scheme: ColorScheme) -> ChorusThemedColors {
        ChorusThemedColors(dark: scheme == .dark)
    }
}
`;
  writeFileSync(resolve(outDir, "Colors.swift"), body);
}

// -------- Palette.swift (ref.palette.*) -------------------------------
{
  const families = Object.keys(t.palette).sort();
  let blocks = "";
  for (const family of families) {
    blocks += `    public enum ${pascal(family)} {\n`;
    for (const step of Object.keys(t.palette[family]).sort((a, b) => Number(a) - Number(b))) {
      blocks += `        public static let ${camel(["s" + step])}: Color = ${swiftHex(t.palette[family][step])}\n`;
    }
    blocks += `    }\n\n`;
  }
  const body = `${header}
/// ref.palette.* — flat reference colors. Most components should reach
/// for ChorusColors (sys.color.*) instead; this is exposed for the rare
/// component (e.g., Chip tag) whose spec explicitly references a
/// translucent neutral that must adapt to whatever surface sits behind.
public enum ChorusPalette {
${blocks.trimEnd()}
}
`;
  writeFileSync(resolve(outDir, "Palette.swift"), body);
}

// -------- Dimensions.swift --------------------------------------------
{
  const block = (name, map) => {
    const lines = Object.keys(map)
      .sort()
      .map((k) => `        public static let ${camel(k.split("-"))}: CGFloat = ${map[k]}`)
      .join("\n");
    return `    public enum ${pascal(name)} {\n${lines}\n    }`;
  };

  const layoutBlocks = ["container", "inline", "stack", "page"]
    .map((g) => block(g, t.layout[g]))
    .join("\n\n");

  const body = `${header}
import CoreGraphics

public enum ChorusLayout {
${layoutBlocks}
}

public enum ChorusRadius {
${Object.keys(t.radius)
  .sort()
  .map((k) => `    public static let ${camel(k.split("-"))}: CGFloat = ${t.radius[k]}`)
  .join("\n")}
}

public enum ChorusBorderWidth {
${Object.keys(t.borderWidth)
  .sort()
  .map((k) => `    public static let ${camel(k.split("-"))}: CGFloat = ${t.borderWidth[k]}`)
  .join("\n")}
}

public enum ChorusIconSize {
${Object.keys(t.iconSize)
  .sort()
  .map((k) => `    public static let ${camel(k.split("-"))}: CGFloat = ${t.iconSize[k]}`)
  .join("\n")}
}

public enum ChorusStateOpacity {
${Object.keys(t.state)
  .sort()
  .map((k) => `    public static let ${camel(k.split("-"))}: Double = ${t.state[k]}`)
  .join("\n")}
}
`;
  writeFileSync(resolve(outDir, "Dimensions.swift"), body);
}

// -------- Typography.swift --------------------------------------------
{
  const trackingPoints = (size, tracking) => {
    // tracking expressed as "<n>em" — convert to points relative to size.
    const m = /^(-?\d*\.?\d+)em$/.exec(tracking);
    if (!m) return 0;
    return Number(m[1]) * size;
  };

  let lines = "";
  for (const role of Object.keys(t.typography).sort()) {
    lines += `    public enum ${pascal(role)} {\n`;
    for (const size of Object.keys(t.typography[role]).sort()) {
      const v = t.typography[role][size];
      const tracking = trackingPoints(v.size, v.tracking).toFixed(4);
      lines += `        public static let ${camel(size.split("-"))} = ChorusTextStyle(size: ${v.size}, weight: ${v.weight}, lineHeight: ${v.lineHeight}, trackingPoints: ${tracking})\n`;
    }
    lines += `    }\n\n`;
  }

  const body = `${header}
import CoreGraphics

/// A typography token resolved into platform-neutral numbers. Apply with
/// \`view.chorusText(ChorusTypography.Label.lg)\` (see ChorusText.swift in
/// the ui-ios package for the SwiftUI modifier).
public struct ChorusTextStyle: Equatable, Hashable {
    public let size: CGFloat
    public let weight: Int
    public let lineHeight: CGFloat   // unitless multiplier
    public let trackingPoints: CGFloat

    public init(size: CGFloat, weight: Int, lineHeight: CGFloat, trackingPoints: CGFloat) {
        self.size = size
        self.weight = weight
        self.lineHeight = lineHeight
        self.trackingPoints = trackingPoints
    }

    /// Mapping the design-token weight numbers (100–900) onto SwiftUI's
    /// \`Font.Weight\` ladder. The spec only uses 400/500/600/700 today.
    public var fontWeight: Font.Weight {
        switch weight {
        case ..<200: return .ultraLight
        case ..<300: return .thin
        case ..<400: return .light
        case ..<500: return .regular
        case ..<600: return .medium
        case ..<700: return .semibold
        case ..<800: return .bold
        case ..<900: return .heavy
        default: return .black
        }
    }
}

public enum ChorusTypography {
${lines.trimEnd()}
}
`;
  writeFileSync(resolve(outDir, "Typography.swift"), body);
}

console.log("[tokens-ios] generated Colors.swift, Palette.swift, Dimensions.swift, Typography.swift");
